# Preliminary Livepeer API server Kubernetes manifest. Should probably grow up to be a big and
# strong Helm chart once this thing doesn't say "prototype" anymore.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  # Delete all old pods before bringing up new ones
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      volumes:
        - name: api-server
          persistentVolumeClaim:
            claimName: api-server

      containers:
        - name: api-server
          livenessProbe:
            httpGet:
              port: 80
              path: /healthz
          readinessProbe:
            httpGet:
              port: 80
              path: /healthz
          image: iameli/livepeer-api-prototype:latest
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
          args:
            - --db-path=/data
          volumeMounts:
            - name: api-server
              mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: retain-storage
  resources:
    requests:
      storage: 2Gi
