account_id = "2d8e3e6f3567c9760d12a19ca2b931b3"
name = "livepeer"
type = "javascript"
workers_dev = false

[env.test]
workers_dev = true

[env.monster]
domain = "livepeer.monster"
zone_id = "21239600972377a5baddef5b4c27eeb4"
route = "livepeer.monster/api/*"

[env.production]
domain = "livepeer.live"
zone_id = "d19b521e26478e5ec28f7cc905a88afa"
route = "*livepeer.live/*"