account_id = "2d8e3e6f3567c9760d12a19ca2b931b3"
name = "livepeer"
type = "javascript"
workers_dev = false

[env.test]
workers_dev = true

[env.monster]
domain = "livepeer.monster"
zone_id = "21239600972377a5baddef5b4c27eeb4"
route = "livepeer.monster/api/*"

[env.com]
domain = "livepeer.com"
zone_id = "ecf6818c4f4e5472d9e453b7d6412042"
route = "livepeer.com/api/*"
